language: ruby
cache:
  - bundler
install:
  - bundle install
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

script:
  - 'bundle exec rake default'
  - gem build sensu-plugins-nexmos.gemspec
  - gem install sensu-plugins-nexmos.gem
